apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: roboshop-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: chaitu1812/{{ .Release.Name }}:{{ .Values.tag }}
          {{- if .Values.secrets.required }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secret
          {{- end }}
          ports:
             - containerPort: {{ .Values.service.containerPort }}
               name: {{ .Release.Name }}-port

