{{- if .Values.ingress.required  }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-ing
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Release.Name }}-lb
    alb.ingress.kubernetes.io/subnets: subnet-062f6abdff28024f5, subnet-05b3bc19d3fe1ba1f
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
spec:
  rules:
    - host: "{{ .Release.Name }}.azcart.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port: {{ .Values.service.port }}

 {{- end }}