{{- if .Values.schemaLoad.required }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.schemaLoad.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "-1"
spec:
  initContainers:
    - name: {{ .Values.schemaLoad.name }}
      image: chaitu1812/load-schema-rhel9
      restartPolicy: Never
      envFrom:
      - secretRef:
          name: {{ .Values.schemaLoad.name }}
{{- end }}



