{{- if .Values.schemaLoad.required }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeed
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: job
          image: chaitu1812/load-schema-rhel9
          env:
          {{- range $key, $value := .Values.schemaLoad.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
      restartPolicy: Never
{{- end }}